import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const backend = process.argv[2];
if (!['codex', 'claude'].includes(backend)) throw new Error('Choose codex or claude.');
const skill = process.argv[3] || 'relentless'; if (!['relentless', 'tune'].includes(skill)) throw new Error('Choose relentless or tune.');
const cwd = fs.mkdtempSync(path.join(os.tmpdir(), `relentless-native-${backend}-`));
fs.writeFileSync(path.join(cwd, 'README.md'), '# SYNTHETIC fixture\nA small reading list idea. No implementation.\n');
const prompt = `${backend === 'codex' ? '$' : '/'}${skill} terminal-only. This is a synthetic skill invocation check. Do not launch a workspace and do not edit anything. ${skill === 'tune' ? 'Review this synthetic feedback: the agent inspected the project before asking and its concrete example helped me answer. No friction or improvement is established. Apply the installed Tune protocol, state its protocol-version metadata, and return a short review. No change needed is valid.' : 'I want to explore a simple reading list for myself. Apply the installed Relentless protocol, state its protocol-version metadata and the distinction between Print and Build, then ask one grounded question.'} Keep the response under 150 words.`;
const args = backend === 'codex' ? ['exec', '--ignore-user-config', '--ignore-rules', '--sandbox', 'read-only', '--skip-git-repo-check', '--model', 'gpt-6-astra', '-c', 'model_reasoning_effort="xhigh"', '--disable', 'plugins', '--disable', 'hooks', '--json', prompt] : ['-p', prompt, '--tools', 'Read,Glob,Grep', '--permission-mode', 'plan', '--setting-sources', 'user', '--strict-mcp-config', '--mcp-config', '{"mcpServers":{}}', '--settings', '{"disableAllHooks":true,"autoMemoryEnabled":false}', '--model', 'claude-fable-5', '--output-format', 'stream-json', '--verbose'];
const child = spawn(backend, args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }); let out = '', err = '';
child.stdout.on('data', d => out += d); child.stderr.on('data', d => err += d);
const timer = setTimeout(() => child.kill('SIGINT'), 180000);
const exit = await new Promise(r => child.once('exit', r)); clearTimeout(timer);
const lines = out.split('\n').flatMap(line => { try { return [JSON.parse(line)]; } catch { return []; } });
const answer = backend === 'codex' ? lines.filter(x => x.type === 'item.completed' && x.item?.type === 'agent_message').map(x => x.item.text).join('\n') : lines.find(x => x.type === 'result')?.result;
const init = lines.find(x => x.type === 'system' && x.subtype === 'init');
console.log(JSON.stringify({ backend, cwd, exit, nativeSkills: init?.skills?.filter(x => /relentless|tune|sprint-prompt/.test(x)), nativeCommands: init?.slash_commands?.filter(x => /relentless|tune|sprint-prompt/.test(x)), answer, error: exit ? err.slice(-2000) : null }, null, 2));
if (exit !== 0 || !answer || answer.includes('Unknown command')) process.exitCode = 1;
