// Behavioral evaluation of the ORIGINAL native interviewer, never a hidden synthesizer.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {randomUUID} from 'node:crypto';
import {chromium} from '@playwright/test';import {startServer} from '../src/server.mjs';import {repo} from '../src/protocol.mjs';import {synthesisInstructions} from '../src/prompts.mjs';import {bridgeConfiguration} from './install-bridge.mjs';import {reconnaissance,decisions} from '../test/fixtures/reconnaissance.mjs';
const variant=process.argv[2];if(!['provisional','settled'].includes(variant))throw new Error('Choose provisional or settled');
const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),`relentless-synthesis-${variant}-`))),project=path.join(root,'project');fs.mkdirSync(project);fs.writeFileSync(path.join(project,'README.md'),'Synthetic fixture only. No remote systems.');
const host=await startServer({root:path.join(root,'private')});let browser,child;
const cfg={...bridgeConfiguration(repo,'codex'),env:{RELENTLESS_HOME:host.store.root,RELENTLESS_NO_OPEN:'1'}};
function toml(v){if(Array.isArray(v))return `[${v.map(toml).join(',')}]`;if(v&&typeof v==='object')return `{${Object.entries(v).map(([k,x])=>`${JSON.stringify(k)}=${toml(x)}`).join(',')}}`;return JSON.stringify(v);}
async function until(check){const start=Date.now();while(Date.now()-start<180000){const v=await check();if(v)return v;await new Promise(r=>setTimeout(r,200));}throw new Error('Synthesis fixture timed out');}
console.log(JSON.stringify({variant,root}));
try{
const prompt=`You are the native interviewer in a sanitized planning evaluation. No real hardware access or execution is authorized. Here is the imported reconnaissance packet:\n${reconnaissance}\nFirst inspect it by thinking, then call open_interview cwd ${JSON.stringify(project)}, title Synthetic secondary-compute planning, intent containing the imported reconnaissance text. Publish a substantive interpretation and unresolved consequential choices. Do not invent decisions. Await sidecar input. If an answer arrives, reconcile it and acknowledge it using one await_interview waitMs1 call, then publish discussion. When Print arrives, synthesize YOURSELF in THIS conversation using the full public context; never create another interviewer. ${synthesisInstructions} Instead of returning the JSON to terminal, publish its prompt/ready/blockers with sourceRevision, promptBaseRevision and exchanges from the latest bridge snapshot. For unanswered choices mark the prompt provisional and ready false, while proposing a useful bounded investigation. If answers resolve them, synthesize the agreed bounded plan and actual verification slices. Preserve exclusions. Acknowledge Print separately and wait. On Return acknowledge and finish without implementing. Do not call any external tools beyond the interaction bridge.`;
const args=['exec','--ignore-user-config','--ignore-rules','--skip-git-repo-check','--sandbox','read-only','--model','gpt-6-astra','--json','-c','model_reasoning_effort="xhigh"','-c','features.shell_tool=false','-c','features.plugins=false','-c','features.apps=false','-c','features.hooks=false','-c',`mcp_servers.relentless=${toml(cfg)}`,'-'];
child=spawn('codex',args,{cwd:project,stdio:['pipe','pipe','pipe']});let log='',err='';child.stdout.on('data',b=>{log+=b;fs.writeFileSync(path.join(root,'native.jsonl'),log);});child.stderr.on('data',b=>err+=b);const done=new Promise(r=>child.on('exit',r));child.stdin.end(prompt);
const id=await until(()=>host.store.list().find(m=>m.attachment)?.id);await until(()=>host.app.attachments.waiters.has(id));
browser=await chromium.launch();const page=await browser.newPage();await page.goto(`${host.origin}/#token=${host.token}&session=${id}`);
if(variant==='settled'){await page.locator('#editor-draft').fill(decisions);await page.getByRole('button',{name:/^Continue/}).click();await until(()=>host.store.meta(id).attachment.events.some(e=>e.kind==='answer'&&e.ack));await until(()=>host.app.attachments.waiters.has(id));}
await page.getByRole('button',{name:'Print',exact:true}).click();await until(()=>host.app.prompts.view(id)?.current);const p=host.app.prompts.view(id);fs.writeFileSync(path.join(root,'evaluated-prompt.md'),p.text);
assert.ok(!/No decisions recorded\.|No unresolved questions\./i.test(p.text));assert.match(p.text,/histor|2025|revalidat/i);assert.match(p.text,/slice/i);assert.match(p.text,/verif|compar|reference/i);
if(variant==='provisional'){assert.equal(p.ready,false);assert.match(p.text,/provisional|investigation.only/i);assert.match(p.text,/environment|Linux|Windows/i);assert.match(p.text,/access|manual|permission/i);}else{assert.match(p.text,/2\s*GiB/i);assert.match(p.text,/60.second|60\s*s\b/i);assert.match(p.text,/one.worker|1.worker|one worker|single.worker/i);assert.match(p.text,/manual/i);assert.match(p.text,/SSH/);assert.match(p.text,/elapsed|resident/i);}
await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('button',{name:'Return to terminal',exact:true}).click();assert.equal(await done,0,err.slice(-1000));assert.deepEqual(fs.readdirSync(project),['README.md']);assert.deepEqual(host.store.meta(id).providers,{});
console.log(JSON.stringify({variant,root,ready:p.ready,blockers:p.blockers,promptRevision:p.revision,prompt:p.text},null,2));
}finally{child?.kill('SIGTERM');await browser?.close();await host.close();}
